### ISSUE TITLE
Document use of `eval()` to parse calculations

### ISSUE THREAD

**Issue by traviskaufman** [MoOx/reduce-css-calc#12]
I noticed that the way math expressions are reduced is by using `eval()` (https://github.com/MoOx/reduce-css-calc/blob/1ce8bd090334a790eb91785a78403af6fcd2f4d1/index.js#L75), however this isn't documented anywhere. Technically, the w3c spec calls for calc to only accept simple binary operators (https://www.w3.org/TR/css3-values/#calc-notation), but with this you could also do things like

``` css
.foo {
  width: calc(2.5px >>> 0);
}
```

See [this codepen](http://codepen.io/traviskaufman/pen/LkOqNp) as an example.

Personally I view this as a feature, and feel like it should be documented rather than just being an implementation detail. What do you think?

**Comment by MoOx** [comment]
I think this is not documented because this is not compatible with specs (and this plugins aims to reduce css calc, following specs). So I don't think it's a good idea. Ideally, eval() should not be used, but I was lazy when I made this.

**Comment by ChALkeR** [comment]
@MoOx Is this still applicable? There is no `eval()` anymore. :wink:

**Comment by MoOx** [comment]
My guess it that the package used still offers more than CSS specs...

**Comment by ben-eb** [comment]
The original example no longer works, as `eval` has been removed from the module. I think it's safe to close this issue, as the intention behind the module is to work with standard syntax. 😄
