### ISSUE TITLE
math-expression-evaluator does allow omitting 0 from decimal number

### ISSUE THREAD

**Issue by bugwheels94** [MoOx/reduce-css-calc#16]
After removing the line 38 it still is passing all the test, may you tell the reason for this comment

```
// CSS allow to omit 0 for 0.* values,
// but math-expression-evaluator does not
```

I want to know the test case for this it failed so that I can correct it. Thanks

**Comment by bugwheels94** [comment]
Oh I forgot to tell that the test are passing because I designed it to omit leading 0s

**Comment by MoOx** [comment]
> because I designed it to omit leading 0s

With version 1.2.9 it was not the case, I added this code to make tests pass. Did you make any change?

**Comment by bugwheels94** [comment]
Yes I did. 1.2.10 was just changed for this purpose https://github.com/redhivesoftware/math-expression-evaluator/commit/d6a82d8225232bbcb33246dc2337ca3a524adc99

**Comment by MoOx** [comment]
Poke @ben-eb

**Comment by ben-eb** [comment]
Yep, all of the current tests pass by changing this line. 👍
