### ISSUE TITLE
Could not reduce expression: calc(0.25em - 1px)?

### ISSUE THREAD

**Issue by davidhund** [MoOx/reduce-css-calc#20]
Hi, I am using `postcss-calc` (which uses `reduce-css-calc` if I'm correct), thanks for your work.

I was under the impression that mixed units should work (I even saw some tests for it) so I am confused why the following throws an error:

```
Could not reduce expression: calc(.25em - 1px) [postcss-calc]
```

I am simply using it as:

```
.c-linklist a {
    display: block;
    padding-top: .25em;
    padding-bottom: calc(.25em - 1px);
}
```

Am I missing something?

**Comment by MoOx** [comment]
Mixed unit can only be computed at runtime, in the browser, so no this module can't handle that. There is not tests for that, just to that check to reduced result does not throw.

**Comment by davidhund** [comment]
Right, makes sense really. Thanks.
