### ISSUE TITLE
Strange unit math in 2.x

### ISSUE THREAD

**Issue by shoomyth** [MoOx/reduce-css-calc#28]
`calc(100vw - (100vw - 100%))`

I'm using this hack to solve ios scroll bug.

1.3.0: `calc(100vw - (100vw - 100%))`
2.0: `calc(0vw - 100%)`

Can't understand new math with different units. This is totally incorrect. I can understand `calc(0vw + 100%)`, but current behavior looks very suspicious.

**Comment by codefo** [comment]
Confirm, I've just reproduced this bug on my project.

**Comment by andyjansson** [comment]
Looks like the following case is wrong: https://github.com/MoOx/reduce-css-calc/blob/master/src/lib/reducer.js#L99 

Mind confirming that it's the only incorrect case?
