### ISSUE TITLE
calc(...)rem adds space between number and unit

### ISSUE THREAD

**Issue by Praneeth-Pike** [MoOx/reduce-css-calc#46]
I'm not sure if this is a dumb thing, but I'm having issue while using cssnext with reduce-css-calc

My Code:
`height: calc(20 / 1.618)rem;`

Output:
`height: 12.36094 rem`

Expected Output:
`height: 12.36094rem`

Is my syntax wrong?

**Comment by Semigradsky** [comment]
@Praneeth-Pike 	I can't reproduce it on last version.
In any case this is not valid css code.
