### ISSUE TITLE
Incorrect values when units are not in lowercase

### ISSUE THREAD

**Issue by moretti** [MoOx/reduce-css-calc#5]
For example `calc(50% - 42Px)` is translated to `calc(0.5 - 42Px)`

(We declare some units in capital case in conjunction with [`postcss-pxtorem`](https://github.com/cuth/postcss-pxtorem#a-message-about-ignoring-properties))

**Comment by MoOx** [comment]
Is this valid per css specs ?

**Comment by moretti** [comment]
Yes, it is. From http://www.w3.org/TR/CSS21/syndata.html:

>  All CSS syntax is case-insensitive within the ASCII range (i.e., [a-z] and [A-Z] are equivalent), except for parts that are not under the control of CSS. For example, the case-sensitivity of values of the HTML attributes "id" and "class", of font names, and of URIs lies outside the scope of this specification. Note in particular that element names are case-insensitive in HTML, but case-sensitive in XML.

**Comment by MoOx** [comment]
So PR is welcome =)

**Comment by MoOx** [comment]
Closed by f881251ef0d74af6447ef7f6fe887f6f3dea286b
