### ISSUE TITLE
Parse error on custom property fallback

### ISSUE THREAD

**Issue by tornqvist** [MoOx/reduce-css-calc#50]
The parser will fail if using nested custom properties with fallbacks which themselves are custom properties.

This code:
```css
.my-class {
  width: calc(var(--xxx, var(--yyy)) / 2);
}
```
Will throw this error:
```
  Error: Parse error on line 1:
  ...ar(--xxx, var(--yyy)) / 2
  -----------------------^
  Expecting 'EOF', 'ADD', 'SUB', 'MUL', 'DIV', got 'RPAREN'
```

I tried putting together a PR using recursive rules for the parser but realized someone else with a better understanding of Bison syntax could do a better job than me.

The best I could come up with is a regex which handles two levels of nesting which is enough for my use case but not really fool proof. I figured I should open an issue before submitting a PR with the following change to the parser:

```diff
- (var\([^\)]*\))                        return 'CSS_VAR';
+ (var\((?:[^)(]+|\((?:[^)(]+|\([^)(]*\))*\))*\))  return 'CSS_VAR';
```

**Comment by AntonTrollback** [comment]
This one I want! But I'm not capable of fixing it… Please help us @MoOx ! ^^
